name: Deploy Healthcare AI System

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ankitraj091/healthcare-ai:v1 -f deployment/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ankitraj091/healthcare-ai:v1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: healthcare-ai-system-ankit
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'docker.io/ankitraj091/healthcare-ai:v1'